### ISSUE TITLE
Labeling subtitle tracks / improving subtitler attribution (meta ticket)

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2187]
@bendk - ref #2181 which led to our conversation the other day about track labels and overwriting.  

There are a few interesting discussion in our support forum regarding amara automatic syncing and attribution, for example: http://support.amara.org/discussions/topics/10131 and http://support.amara.org/support/discussions/topics/8513.  Both are old threads but still relevant.

The second post links to this video which shows how 1 set of subs were labeled with the translator names.  Giving the amount of space youtube provides, it seems like that could get very lengthy, but is a nice way of acknowledging contributions.

![image](https://cloud.githubusercontent.com/assets/299270/7316661/1be133da-ea79-11e4-9ee7-902d24bc0fd4.png)

Another nice thing about the youtube attribute in the label is that when you switch CC on for the language, that full track name shows at the top: 

![image](https://cloud.githubusercontent.com/assets/299270/7316714/9ed433f0-ea79-11e4-8ae2-181b3292d847.png)

It also shows when you change the language track in the transcript view:

![image](https://cloud.githubusercontent.com/assets/299270/7316730/c954059c-ea79-11e4-81a6-235914c557f9.png)

For amara here are some suggestions (can make individual tickets later):

- [ ] 1. for non-team crowd captions label the track sent to youtube with ```by the Amara.org crowd```
- [ ] 2. for team captions label the track ```by [Team name] | Amara.org```
- [ ] 3. In the Amara embedder - add a line above the transcript that would list all contributors.
![image](https://cloud.githubusercontent.com/assets/299270/7317086/faea2d40-ea7c-11e4-997c-d1508b6b82a4.png)
- [ ] 4. In the Amara embedder - possibly overlay something on the video when switching languages that lists the contributors, similar to what youtube does.
- [ ] 5. Possibly in the embedder, displaying the credits should be an optional parameter.

**Comment by jdragojevic** [comment]
@PCF-Testing made a good point about some teams not wanting the particular team name shown as-is.  So maybe it would be better as some type of opt-in configuration.

**Comment by bendk** [comment]
I'm not a huge fan of 1 and 2.  Personally, I think the track labels should just describe what the track is and not include the credits.  That said, I know some teams will love a feature like this.  I think opt-in is the best and maybe we should try to label the subtitle author since that's the way it's being used.  I know there are issues with doing that, but TED has an algorithm that seems to work for them most of the time, and they could change the subtitle track others.

I love 3/4.  I'm so-so on 5, maybe we should wait for someone to actually request that feature.
