### ISSUE TITLE
Makeover of the personal dashboard

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3107]
@PCF-Testing commented on [Thu Feb 01 2018](https://github.com/pculture/amara-enterprise/issues/1852)

Create a v2.0 page for the personal dashboard.

This should include:
- [ ] Making activity lists expandable (https://github.com/pculture/unisubs/issues/568)
- [ ] Fixing the links (https://github.com/pculture/amara-enterprise/issues/1681)
- [ ] Adding new aggregate feeds of assignments across the user's teams (https://github.com/pculture/unisubs/issues/2735)
- [ ] Gracefully handle long video URLs so that they don't break the layout (https://github.com/pculture/unisubs/issues/351)

---

@kslottow commented on [Thu Feb 01 2018](https://github.com/pculture/amara-enterprise/issues/1852#issuecomment-362397450)

Suggestions from Spanish linguists at meetup (Eduardo and Carolina):

A way to see if there are available assignments in any of your teams at a glance
